import esbuild from 'esbuild';
import { compile } from '@vue/compiler-dom';
import { writeFileSync } from 'node:fs';
import { template } from './src/template.ts';

// Precompile the template to a render function at BUILD time. This lets us ship
// the runtime-only Vue build (no template compiler) and — critically — avoids
// `new Function`/eval at runtime, so the app runs under a strict CSP with no
// 'unsafe-eval'. Output imports its render helpers from 'vue'.
const { code } = compile(template, { mode: 'module', hoistStatic: true, prefixIdentifiers: true });
writeFileSync('./src/render.generated.ts', '// @ts-nocheck — generated by build.mjs from template.ts\n' + code);
console.log('compiled render.generated.ts');

// Bundle the TypeScript SPA + runtime-only Vue + Zod into a single self-contained
// IIFE that the Go binary embeds and serves. No CDN, no eval.
await esbuild.build({
  entryPoints: ['src/main.ts'],
  bundle: true,
  minify: true,
  format: 'iife',
  target: 'es2020',
  legalComments: 'none',
  outfile: '../assets/app.js',
  alias: { vue: 'vue/dist/vue.runtime.esm-browser.prod.js' },
  define: {
    __VUE_OPTIONS_API__: 'true',
    __VUE_PROD_DEVTOOLS__: 'false',
    __VUE_PROD_HYDRATION_MISMATCH_DETAILS__: 'false',
  },
});
console.log('built ../assets/app.js');
