// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: rollops/plugin/v1/plugin.proto

package rollopspluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Spec          []byte                 `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Checksum      string                 `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyRequest) Reset() {
	*x = ApplyRequest{}
	mi := &file_rollops_plugin_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest) ProtoMessage() {}

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rollops_plugin_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest.ProtoReflect.Descriptor instead.
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return file_rollops_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *ApplyRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ApplyRequest) GetSpec() []byte {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *ApplyRequest) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

type ApplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changed       bool                   `protobuf:"varint,1,opt,name=changed,proto3" json:"changed,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyResponse) Reset() {
	*x = ApplyResponse{}
	mi := &file_rollops_plugin_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResponse) ProtoMessage() {}

func (x *ApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rollops_plugin_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResponse.ProtoReflect.Descriptor instead.
func (*ApplyResponse) Descriptor() ([]byte, []int) {
	return file_rollops_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *ApplyResponse) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

func (x *ApplyResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type ObserveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObserveRequest) Reset() {
	*x = ObserveRequest{}
	mi := &file_rollops_plugin_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserveRequest) ProtoMessage() {}

func (x *ObserveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rollops_plugin_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserveRequest.ProtoReflect.Descriptor instead.
func (*ObserveRequest) Descriptor() ([]byte, []int) {
	return file_rollops_plugin_v1_plugin_proto_rawDescGZIP(), []int{2}
}

type ObserveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Meta          map[string]string      `protobuf:"bytes,2,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObserveResponse) Reset() {
	*x = ObserveResponse{}
	mi := &file_rollops_plugin_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserveResponse) ProtoMessage() {}

func (x *ObserveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rollops_plugin_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserveResponse.ProtoReflect.Descriptor instead.
func (*ObserveResponse) Descriptor() ([]byte, []int) {
	return file_rollops_plugin_v1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *ObserveResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ObserveResponse) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_rollops_plugin_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rollops_plugin_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_rollops_plugin_v1_plugin_proto_rawDescGZIP(), []int{4}
}

type HealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 1 = healthy, 2 = degraded, 3 = unhealthy (pkg/target.HealthState).
	State         int32  `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_rollops_plugin_v1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rollops_plugin_v1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_rollops_plugin_v1_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *HealthResponse) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *HealthResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_rollops_plugin_v1_plugin_proto protoreflect.FileDescriptor

const file_rollops_plugin_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x1erollops/plugin/v1/plugin.proto\x12\x11rollops.plugin.v1\"R\n" +
	"\fApplyRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04spec\x18\x02 \x01(\fR\x04spec\x12\x1a\n" +
	"\bchecksum\x18\x03 \x01(\tR\bchecksum\"A\n" +
	"\rApplyResponse\x12\x18\n" +
	"\achanged\x18\x01 \x01(\bR\achanged\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"\x10\n" +
	"\x0eObserveRequest\"\xa2\x01\n" +
	"\x0fObserveResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12@\n" +
	"\x04meta\x18\x02 \x03(\v2,.rollops.plugin.v1.ObserveResponse.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x0f\n" +
	"\rHealthRequest\">\n" +
	"\x0eHealthResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\x05R\x05state\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2\xfb\x01\n" +
	"\fTargetPlugin\x12J\n" +
	"\x05Apply\x12\x1f.rollops.plugin.v1.ApplyRequest\x1a .rollops.plugin.v1.ApplyResponse\x12P\n" +
	"\aObserve\x12!.rollops.plugin.v1.ObserveRequest\x1a\".rollops.plugin.v1.ObserveResponse\x12M\n" +
	"\x06Health\x12 .rollops.plugin.v1.HealthRequest\x1a!.rollops.plugin.v1.HealthResponseBCZAgo.klarlabs.de/rollops/pkg/plugin/rollopspluginv1;rollopspluginv1b\x06proto3"

var (
	file_rollops_plugin_v1_plugin_proto_rawDescOnce sync.Once
	file_rollops_plugin_v1_plugin_proto_rawDescData []byte
)

func file_rollops_plugin_v1_plugin_proto_rawDescGZIP() []byte {
	file_rollops_plugin_v1_plugin_proto_rawDescOnce.Do(func() {
		file_rollops_plugin_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rollops_plugin_v1_plugin_proto_rawDesc), len(file_rollops_plugin_v1_plugin_proto_rawDesc)))
	})
	return file_rollops_plugin_v1_plugin_proto_rawDescData
}

var file_rollops_plugin_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_rollops_plugin_v1_plugin_proto_goTypes = []any{
	(*ApplyRequest)(nil),    // 0: rollops.plugin.v1.ApplyRequest
	(*ApplyResponse)(nil),   // 1: rollops.plugin.v1.ApplyResponse
	(*ObserveRequest)(nil),  // 2: rollops.plugin.v1.ObserveRequest
	(*ObserveResponse)(nil), // 3: rollops.plugin.v1.ObserveResponse
	(*HealthRequest)(nil),   // 4: rollops.plugin.v1.HealthRequest
	(*HealthResponse)(nil),  // 5: rollops.plugin.v1.HealthResponse
	nil,                     // 6: rollops.plugin.v1.ObserveResponse.MetaEntry
}
var file_rollops_plugin_v1_plugin_proto_depIdxs = []int32{
	6, // 0: rollops.plugin.v1.ObserveResponse.meta:type_name -> rollops.plugin.v1.ObserveResponse.MetaEntry
	0, // 1: rollops.plugin.v1.TargetPlugin.Apply:input_type -> rollops.plugin.v1.ApplyRequest
	2, // 2: rollops.plugin.v1.TargetPlugin.Observe:input_type -> rollops.plugin.v1.ObserveRequest
	4, // 3: rollops.plugin.v1.TargetPlugin.Health:input_type -> rollops.plugin.v1.HealthRequest
	1, // 4: rollops.plugin.v1.TargetPlugin.Apply:output_type -> rollops.plugin.v1.ApplyResponse
	3, // 5: rollops.plugin.v1.TargetPlugin.Observe:output_type -> rollops.plugin.v1.ObserveResponse
	5, // 6: rollops.plugin.v1.TargetPlugin.Health:output_type -> rollops.plugin.v1.HealthResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rollops_plugin_v1_plugin_proto_init() }
func file_rollops_plugin_v1_plugin_proto_init() {
	if File_rollops_plugin_v1_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rollops_plugin_v1_plugin_proto_rawDesc), len(file_rollops_plugin_v1_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rollops_plugin_v1_plugin_proto_goTypes,
		DependencyIndexes: file_rollops_plugin_v1_plugin_proto_depIdxs,
		MessageInfos:      file_rollops_plugin_v1_plugin_proto_msgTypes,
	}.Build()
	File_rollops_plugin_v1_plugin_proto = out.File
	file_rollops_plugin_v1_plugin_proto_goTypes = nil
	file_rollops_plugin_v1_plugin_proto_depIdxs = nil
}
