// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.0
// source: rollops/plugin/v1/plugin.proto

package rollopspluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TargetPlugin_Apply_FullMethodName   = "/rollops.plugin.v1.TargetPlugin/Apply"
	TargetPlugin_Observe_FullMethodName = "/rollops.plugin.v1.TargetPlugin/Observe"
	TargetPlugin_Health_FullMethodName  = "/rollops.plugin.v1.TargetPlugin/Health"
)

// TargetPluginClient is the client API for TargetPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TargetPlugin is the wire a third-party target plugin serves. The host
// (rollops) launches the plugin binary, reads the handshake line from stdout,
// dials this service on the advertised unix socket, and adapts it into the
// pkg/target.Target contract. Semantics (idempotent apply, stable fingerprint,
// concrete health, no secret leakage) are defined in docs/target-plugins.md and
// enforced by pkg/conformance.
type TargetPluginClient interface {
	Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*ApplyResponse, error)
	Observe(ctx context.Context, in *ObserveRequest, opts ...grpc.CallOption) (*ObserveResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type targetPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewTargetPluginClient(cc grpc.ClientConnInterface) TargetPluginClient {
	return &targetPluginClient{cc}
}

func (c *targetPluginClient) Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*ApplyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyResponse)
	err := c.cc.Invoke(ctx, TargetPlugin_Apply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetPluginClient) Observe(ctx context.Context, in *ObserveRequest, opts ...grpc.CallOption) (*ObserveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObserveResponse)
	err := c.cc.Invoke(ctx, TargetPlugin_Observe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetPluginClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, TargetPlugin_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TargetPluginServer is the server API for TargetPlugin service.
// All implementations must embed UnimplementedTargetPluginServer
// for forward compatibility.
//
// TargetPlugin is the wire a third-party target plugin serves. The host
// (rollops) launches the plugin binary, reads the handshake line from stdout,
// dials this service on the advertised unix socket, and adapts it into the
// pkg/target.Target contract. Semantics (idempotent apply, stable fingerprint,
// concrete health, no secret leakage) are defined in docs/target-plugins.md and
// enforced by pkg/conformance.
type TargetPluginServer interface {
	Apply(context.Context, *ApplyRequest) (*ApplyResponse, error)
	Observe(context.Context, *ObserveRequest) (*ObserveResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedTargetPluginServer()
}

// UnimplementedTargetPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTargetPluginServer struct{}

func (UnimplementedTargetPluginServer) Apply(context.Context, *ApplyRequest) (*ApplyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Apply not implemented")
}
func (UnimplementedTargetPluginServer) Observe(context.Context, *ObserveRequest) (*ObserveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Observe not implemented")
}
func (UnimplementedTargetPluginServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedTargetPluginServer) mustEmbedUnimplementedTargetPluginServer() {}
func (UnimplementedTargetPluginServer) testEmbeddedByValue()                      {}

// UnsafeTargetPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TargetPluginServer will
// result in compilation errors.
type UnsafeTargetPluginServer interface {
	mustEmbedUnimplementedTargetPluginServer()
}

func RegisterTargetPluginServer(s grpc.ServiceRegistrar, srv TargetPluginServer) {
	// If the following call panics, it indicates UnimplementedTargetPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TargetPlugin_ServiceDesc, srv)
}

func _TargetPlugin_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetPluginServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetPlugin_Apply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetPluginServer).Apply(ctx, req.(*ApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetPlugin_Observe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObserveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetPluginServer).Observe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetPlugin_Observe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetPluginServer).Observe(ctx, req.(*ObserveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetPlugin_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetPluginServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetPlugin_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetPluginServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TargetPlugin_ServiceDesc is the grpc.ServiceDesc for TargetPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TargetPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rollops.plugin.v1.TargetPlugin",
	HandlerType: (*TargetPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Apply",
			Handler:    _TargetPlugin_Apply_Handler,
		},
		{
			MethodName: "Observe",
			Handler:    _TargetPlugin_Observe_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _TargetPlugin_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rollops/plugin/v1/plugin.proto",
}
