// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.0
// source: rollops/v1/rollops.proto

package rollopsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RolloutService_Plan_FullMethodName     = "/rollops.v1.RolloutService/Plan"
	RolloutService_Apply_FullMethodName    = "/rollops.v1.RolloutService/Apply"
	RolloutService_Status_FullMethodName   = "/rollops.v1.RolloutService/Status"
	RolloutService_Rollback_FullMethodName = "/rollops.v1.RolloutService/Rollback"
	RolloutService_Approve_FullMethodName  = "/rollops.v1.RolloutService/Approve"
	RolloutService_Reject_FullMethodName   = "/rollops.v1.RolloutService/Reject"
	RolloutService_Promote_FullMethodName  = "/rollops.v1.RolloutService/Promote"
	RolloutService_Verify_FullMethodName   = "/rollops.v1.RolloutService/Verify"
	RolloutService_Freeze_FullMethodName   = "/rollops.v1.RolloutService/Freeze"
)

// RolloutServiceClient is the client API for RolloutService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RolloutService is the typed gRPC surface over the engine — the daemon
// transport the CLI and agents use. RPCs map 1:1 to engine operations; the
// browser UI uses the HTTP/JSON surface (internal/api). Every call is
// authenticated (bearer token in the "authorization" metadata by default) and
// authorized via RBAC.
type RolloutServiceClient interface {
	// Plan shows what an apply would change.
	Plan(ctx context.Context, in *PlanRequest, opts ...grpc.CallOption) (*PlanResponse, error)
	// Apply deploys desired state.
	Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*ApplyResponse, error)
	// Status returns a rollout's current state.
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// Rollback rolls a target back to its previous desired state.
	Rollback(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResponse, error)
	// Approve approves a rollout awaiting approval (and deploys it).
	Approve(ctx context.Context, in *RolloutActionRequest, opts ...grpc.CallOption) (*RolloutActionResponse, error)
	// Reject rejects a rollout awaiting approval.
	Reject(ctx context.Context, in *RolloutActionRequest, opts ...grpc.CallOption) (*RolloutActionResponse, error)
	// Promote marks a verified rollout promoted.
	Promote(ctx context.Context, in *RolloutActionRequest, opts ...grpc.CallOption) (*RolloutActionResponse, error)
	// Verify DRY-RUNS the post-deploy gate (health, smoke, metric analysis) and
	// reports each one. It changes nothing: no phase transition, no promotion,
	// no rollback. The gates themselves do run — a configured smoke test executes
	// its command on the daemon host.
	Verify(ctx context.Context, in *RolloutActionRequest, opts ...grpc.CallOption) (*VerifyResponse, error)
	// Freeze engages or lifts the emergency kill-switch that blocks all applies.
	Freeze(ctx context.Context, in *FreezeRequest, opts ...grpc.CallOption) (*FreezeResponse, error)
}

type rolloutServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRolloutServiceClient(cc grpc.ClientConnInterface) RolloutServiceClient {
	return &rolloutServiceClient{cc}
}

func (c *rolloutServiceClient) Plan(ctx context.Context, in *PlanRequest, opts ...grpc.CallOption) (*PlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanResponse)
	err := c.cc.Invoke(ctx, RolloutService_Plan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolloutServiceClient) Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*ApplyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyResponse)
	err := c.cc.Invoke(ctx, RolloutService_Apply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolloutServiceClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, RolloutService_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolloutServiceClient) Rollback(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollbackResponse)
	err := c.cc.Invoke(ctx, RolloutService_Rollback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolloutServiceClient) Approve(ctx context.Context, in *RolloutActionRequest, opts ...grpc.CallOption) (*RolloutActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RolloutActionResponse)
	err := c.cc.Invoke(ctx, RolloutService_Approve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolloutServiceClient) Reject(ctx context.Context, in *RolloutActionRequest, opts ...grpc.CallOption) (*RolloutActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RolloutActionResponse)
	err := c.cc.Invoke(ctx, RolloutService_Reject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolloutServiceClient) Promote(ctx context.Context, in *RolloutActionRequest, opts ...grpc.CallOption) (*RolloutActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RolloutActionResponse)
	err := c.cc.Invoke(ctx, RolloutService_Promote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolloutServiceClient) Verify(ctx context.Context, in *RolloutActionRequest, opts ...grpc.CallOption) (*VerifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyResponse)
	err := c.cc.Invoke(ctx, RolloutService_Verify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolloutServiceClient) Freeze(ctx context.Context, in *FreezeRequest, opts ...grpc.CallOption) (*FreezeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FreezeResponse)
	err := c.cc.Invoke(ctx, RolloutService_Freeze_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RolloutServiceServer is the server API for RolloutService service.
// All implementations must embed UnimplementedRolloutServiceServer
// for forward compatibility.
//
// RolloutService is the typed gRPC surface over the engine — the daemon
// transport the CLI and agents use. RPCs map 1:1 to engine operations; the
// browser UI uses the HTTP/JSON surface (internal/api). Every call is
// authenticated (bearer token in the "authorization" metadata by default) and
// authorized via RBAC.
type RolloutServiceServer interface {
	// Plan shows what an apply would change.
	Plan(context.Context, *PlanRequest) (*PlanResponse, error)
	// Apply deploys desired state.
	Apply(context.Context, *ApplyRequest) (*ApplyResponse, error)
	// Status returns a rollout's current state.
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	// Rollback rolls a target back to its previous desired state.
	Rollback(context.Context, *RollbackRequest) (*RollbackResponse, error)
	// Approve approves a rollout awaiting approval (and deploys it).
	Approve(context.Context, *RolloutActionRequest) (*RolloutActionResponse, error)
	// Reject rejects a rollout awaiting approval.
	Reject(context.Context, *RolloutActionRequest) (*RolloutActionResponse, error)
	// Promote marks a verified rollout promoted.
	Promote(context.Context, *RolloutActionRequest) (*RolloutActionResponse, error)
	// Verify DRY-RUNS the post-deploy gate (health, smoke, metric analysis) and
	// reports each one. It changes nothing: no phase transition, no promotion,
	// no rollback. The gates themselves do run — a configured smoke test executes
	// its command on the daemon host.
	Verify(context.Context, *RolloutActionRequest) (*VerifyResponse, error)
	// Freeze engages or lifts the emergency kill-switch that blocks all applies.
	Freeze(context.Context, *FreezeRequest) (*FreezeResponse, error)
	mustEmbedUnimplementedRolloutServiceServer()
}

// UnimplementedRolloutServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRolloutServiceServer struct{}

func (UnimplementedRolloutServiceServer) Plan(context.Context, *PlanRequest) (*PlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Plan not implemented")
}
func (UnimplementedRolloutServiceServer) Apply(context.Context, *ApplyRequest) (*ApplyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Apply not implemented")
}
func (UnimplementedRolloutServiceServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedRolloutServiceServer) Rollback(context.Context, *RollbackRequest) (*RollbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Rollback not implemented")
}
func (UnimplementedRolloutServiceServer) Approve(context.Context, *RolloutActionRequest) (*RolloutActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Approve not implemented")
}
func (UnimplementedRolloutServiceServer) Reject(context.Context, *RolloutActionRequest) (*RolloutActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reject not implemented")
}
func (UnimplementedRolloutServiceServer) Promote(context.Context, *RolloutActionRequest) (*RolloutActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Promote not implemented")
}
func (UnimplementedRolloutServiceServer) Verify(context.Context, *RolloutActionRequest) (*VerifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Verify not implemented")
}
func (UnimplementedRolloutServiceServer) Freeze(context.Context, *FreezeRequest) (*FreezeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Freeze not implemented")
}
func (UnimplementedRolloutServiceServer) mustEmbedUnimplementedRolloutServiceServer() {}
func (UnimplementedRolloutServiceServer) testEmbeddedByValue()                        {}

// UnsafeRolloutServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RolloutServiceServer will
// result in compilation errors.
type UnsafeRolloutServiceServer interface {
	mustEmbedUnimplementedRolloutServiceServer()
}

func RegisterRolloutServiceServer(s grpc.ServiceRegistrar, srv RolloutServiceServer) {
	// If the following call panics, it indicates UnimplementedRolloutServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RolloutService_ServiceDesc, srv)
}

func _RolloutService_Plan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolloutServiceServer).Plan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolloutService_Plan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolloutServiceServer).Plan(ctx, req.(*PlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RolloutService_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolloutServiceServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolloutService_Apply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolloutServiceServer).Apply(ctx, req.(*ApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RolloutService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolloutServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolloutService_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolloutServiceServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RolloutService_Rollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolloutServiceServer).Rollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolloutService_Rollback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolloutServiceServer).Rollback(ctx, req.(*RollbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RolloutService_Approve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RolloutActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolloutServiceServer).Approve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolloutService_Approve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolloutServiceServer).Approve(ctx, req.(*RolloutActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RolloutService_Reject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RolloutActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolloutServiceServer).Reject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolloutService_Reject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolloutServiceServer).Reject(ctx, req.(*RolloutActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RolloutService_Promote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RolloutActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolloutServiceServer).Promote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolloutService_Promote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolloutServiceServer).Promote(ctx, req.(*RolloutActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RolloutService_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RolloutActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolloutServiceServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolloutService_Verify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolloutServiceServer).Verify(ctx, req.(*RolloutActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RolloutService_Freeze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FreezeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolloutServiceServer).Freeze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolloutService_Freeze_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolloutServiceServer).Freeze(ctx, req.(*FreezeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RolloutService_ServiceDesc is the grpc.ServiceDesc for RolloutService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RolloutService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rollops.v1.RolloutService",
	HandlerType: (*RolloutServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Plan",
			Handler:    _RolloutService_Plan_Handler,
		},
		{
			MethodName: "Apply",
			Handler:    _RolloutService_Apply_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _RolloutService_Status_Handler,
		},
		{
			MethodName: "Rollback",
			Handler:    _RolloutService_Rollback_Handler,
		},
		{
			MethodName: "Approve",
			Handler:    _RolloutService_Approve_Handler,
		},
		{
			MethodName: "Reject",
			Handler:    _RolloutService_Reject_Handler,
		},
		{
			MethodName: "Promote",
			Handler:    _RolloutService_Promote_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _RolloutService_Verify_Handler,
		},
		{
			MethodName: "Freeze",
			Handler:    _RolloutService_Freeze_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rollops/v1/rollops.proto",
}
