// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: rollops/v1/rollops.proto

package rollopsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlanRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// config is the rollout config YAML.
	Config        string `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanRequest) Reset() {
	*x = PlanRequest{}
	mi := &file_rollops_v1_rollops_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanRequest) ProtoMessage() {}

func (x *PlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rollops_v1_rollops_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanRequest.ProtoReflect.Descriptor instead.
func (*PlanRequest) Descriptor() ([]byte, []int) {
	return file_rollops_v1_rollops_proto_rawDescGZIP(), []int{0}
}

func (x *PlanRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type PlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"` // create | update | noop
	Changed       bool                   `protobuf:"varint,2,opt,name=changed,proto3" json:"changed,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanResponse) Reset() {
	*x = PlanResponse{}
	mi := &file_rollops_v1_rollops_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanResponse) ProtoMessage() {}

func (x *PlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rollops_v1_rollops_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanResponse.ProtoReflect.Descriptor instead.
func (*PlanResponse) Descriptor() ([]byte, []int) {
	return file_rollops_v1_rollops_proto_rawDescGZIP(), []int{1}
}

func (x *PlanResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PlanResponse) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

func (x *PlanResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type ApplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        string                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyRequest) Reset() {
	*x = ApplyRequest{}
	mi := &file_rollops_v1_rollops_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest) ProtoMessage() {}

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rollops_v1_rollops_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest.ProtoReflect.Descriptor instead.
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return file_rollops_v1_rollops_proto_rawDescGZIP(), []int{2}
}

func (x *ApplyRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type ApplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Phase         string                 `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyResponse) Reset() {
	*x = ApplyResponse{}
	mi := &file_rollops_v1_rollops_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResponse) ProtoMessage() {}

func (x *ApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rollops_v1_rollops_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResponse.ProtoReflect.Descriptor instead.
func (*ApplyResponse) Descriptor() ([]byte, []int) {
	return file_rollops_v1_rollops_proto_rawDescGZIP(), []int{3}
}

func (x *ApplyResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApplyResponse) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *ApplyResponse) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_rollops_v1_rollops_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rollops_v1_rollops_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_rollops_v1_rollops_proto_rawDescGZIP(), []int{4}
}

func (x *StatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StatusResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Phase    string                 `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	Target   string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Strategy string                 `protobuf:"bytes,4,opt,name=strategy,proto3" json:"strategy,omitempty"`
	// Progressive step progress: the last step that passed its health gate
	// (1-based), the plan's total, and the current traffic weight. All zero
	// when the strategy has not started stepping.
	StepIndex     int32  `protobuf:"varint,5,opt,name=step_index,json=stepIndex,proto3" json:"step_index,omitempty"`
	StepTotal     int32  `protobuf:"varint,6,opt,name=step_total,json=stepTotal,proto3" json:"step_total,omitempty"`
	StepWeight    int32  `protobuf:"varint,7,opt,name=step_weight,json=stepWeight,proto3" json:"step_weight,omitempty"`
	Note          string `protobuf:"bytes,8,opt,name=note,proto3" json:"note,omitempty"` // latest transition note (e.g. "database rollback: succeeded")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_rollops_v1_rollops_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rollops_v1_rollops_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_rollops_v1_rollops_proto_rawDescGZIP(), []int{5}
}

func (x *StatusResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StatusResponse) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *StatusResponse) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *StatusResponse) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *StatusResponse) GetStepIndex() int32 {
	if x != nil {
		return x.StepIndex
	}
	return 0
}

func (x *StatusResponse) GetStepTotal() int32 {
	if x != nil {
		return x.StepTotal
	}
	return 0
}

func (x *StatusResponse) GetStepWeight() int32 {
	if x != nil {
		return x.StepWeight
	}
	return 0
}

func (x *StatusResponse) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type RollbackRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Target string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	// force overrides the backward-compatibility gate: roll back even when the
	// release ran a database migration not declared backwardCompatible and has no
	// reverse command configured.
	Force         bool `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackRequest) Reset() {
	*x = RollbackRequest{}
	mi := &file_rollops_v1_rollops_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackRequest) ProtoMessage() {}

func (x *RollbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rollops_v1_rollops_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackRequest.ProtoReflect.Descriptor instead.
func (*RollbackRequest) Descriptor() ([]byte, []int) {
	return file_rollops_v1_rollops_proto_rawDescGZIP(), []int{6}
}

func (x *RollbackRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *RollbackRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type RollbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Phase         string                 `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackResponse) Reset() {
	*x = RollbackResponse{}
	mi := &file_rollops_v1_rollops_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackResponse) ProtoMessage() {}

func (x *RollbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rollops_v1_rollops_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackResponse.ProtoReflect.Descriptor instead.
func (*RollbackResponse) Descriptor() ([]byte, []int) {
	return file_rollops_v1_rollops_proto_rawDescGZIP(), []int{7}
}

func (x *RollbackResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RollbackResponse) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *RollbackResponse) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

// RolloutActionRequest identifies a rollout by id for
// approve/reject/promote/verify.
type RolloutActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolloutActionRequest) Reset() {
	*x = RolloutActionRequest{}
	mi := &file_rollops_v1_rollops_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolloutActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolloutActionRequest) ProtoMessage() {}

func (x *RolloutActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rollops_v1_rollops_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolloutActionRequest.ProtoReflect.Descriptor instead.
func (*RolloutActionRequest) Descriptor() ([]byte, []int) {
	return file_rollops_v1_rollops_proto_rawDescGZIP(), []int{8}
}

func (x *RolloutActionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RolloutActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Phase         string                 `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Note          string                 `protobuf:"bytes,4,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolloutActionResponse) Reset() {
	*x = RolloutActionResponse{}
	mi := &file_rollops_v1_rollops_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolloutActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolloutActionResponse) ProtoMessage() {}

func (x *RolloutActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rollops_v1_rollops_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolloutActionResponse.ProtoReflect.Descriptor instead.
func (*RolloutActionResponse) Descriptor() ([]byte, []int) {
	return file_rollops_v1_rollops_proto_rawDescGZIP(), []int{9}
}

func (x *RolloutActionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RolloutActionResponse) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *RolloutActionResponse) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *RolloutActionResponse) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

// GateResult is one post-deploy gate's outcome in a dry-run verification.
type GateResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// gate is "health", "smoke" or "analysis".
	Gate string `protobuf:"bytes,1,opt,name=gate,proto3" json:"gate,omitempty"`
	// status is "pass", "fail", "skipped" (not configured) or "not-run"
	// (short-circuited by an earlier failure).
	Status        string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Detail        string `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GateResult) Reset() {
	*x = GateResult{}
	mi := &file_rollops_v1_rollops_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GateResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateResult) ProtoMessage() {}

func (x *GateResult) ProtoReflect() protoreflect.Message {
	mi := &file_rollops_v1_rollops_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateResult.ProtoReflect.Descriptor instead.
func (*GateResult) Descriptor() ([]byte, []int) {
	return file_rollops_v1_rollops_proto_rawDescGZIP(), []int{10}
}

func (x *GateResult) GetGate() string {
	if x != nil {
		return x.Gate
	}
	return ""
}

func (x *GateResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GateResult) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// VerifyResponse is the outcome of a dry-run verification. The phase is
// reported, never changed.
type VerifyResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Phase  string                 `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	Target string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	// ok is true when no gate failed.
	Ok bool `protobuf:"varint,4,opt,name=ok,proto3" json:"ok,omitempty"`
	// reason is the first failing gate's detail; empty when ok.
	Reason        string        `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	Gates         []*GateResult `protobuf:"bytes,6,rep,name=gates,proto3" json:"gates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyResponse) Reset() {
	*x = VerifyResponse{}
	mi := &file_rollops_v1_rollops_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResponse) ProtoMessage() {}

func (x *VerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rollops_v1_rollops_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResponse.ProtoReflect.Descriptor instead.
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return file_rollops_v1_rollops_proto_rawDescGZIP(), []int{11}
}

func (x *VerifyResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VerifyResponse) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *VerifyResponse) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *VerifyResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *VerifyResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *VerifyResponse) GetGates() []*GateResult {
	if x != nil {
		return x.Gates
	}
	return nil
}

type FreezeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"` // true engages the freeze, false lifts it
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`  // recorded when engaging
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FreezeRequest) Reset() {
	*x = FreezeRequest{}
	mi := &file_rollops_v1_rollops_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FreezeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreezeRequest) ProtoMessage() {}

func (x *FreezeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rollops_v1_rollops_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreezeRequest.ProtoReflect.Descriptor instead.
func (*FreezeRequest) Descriptor() ([]byte, []int) {
	return file_rollops_v1_rollops_proto_rawDescGZIP(), []int{12}
}

func (x *FreezeRequest) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *FreezeRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type FreezeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FreezeResponse) Reset() {
	*x = FreezeResponse{}
	mi := &file_rollops_v1_rollops_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FreezeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreezeResponse) ProtoMessage() {}

func (x *FreezeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rollops_v1_rollops_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreezeResponse.ProtoReflect.Descriptor instead.
func (*FreezeResponse) Descriptor() ([]byte, []int) {
	return file_rollops_v1_rollops_proto_rawDescGZIP(), []int{13}
}

func (x *FreezeResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *FreezeResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_rollops_v1_rollops_proto protoreflect.FileDescriptor

const file_rollops_v1_rollops_proto_rawDesc = "" +
	"\n" +
	"\x18rollops/v1/rollops.proto\x12\n" +
	"rollops.v1\"%\n" +
	"\vPlanRequest\x12\x16\n" +
	"\x06config\x18\x01 \x01(\tR\x06config\"Z\n" +
	"\fPlanResponse\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x18\n" +
	"\achanged\x18\x02 \x01(\bR\achanged\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\"&\n" +
	"\fApplyRequest\x12\x16\n" +
	"\x06config\x18\x01 \x01(\tR\x06config\"M\n" +
	"\rApplyResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\"\x1f\n" +
	"\rStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xdd\x01\n" +
	"\x0eStatusResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x1a\n" +
	"\bstrategy\x18\x04 \x01(\tR\bstrategy\x12\x1d\n" +
	"\n" +
	"step_index\x18\x05 \x01(\x05R\tstepIndex\x12\x1d\n" +
	"\n" +
	"step_total\x18\x06 \x01(\x05R\tstepTotal\x12\x1f\n" +
	"\vstep_weight\x18\a \x01(\x05R\n" +
	"stepWeight\x12\x12\n" +
	"\x04note\x18\b \x01(\tR\x04note\"?\n" +
	"\x0fRollbackRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"P\n" +
	"\x10RollbackResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\"&\n" +
	"\x14RolloutActionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"i\n" +
	"\x15RolloutActionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x12\n" +
	"\x04note\x18\x04 \x01(\tR\x04note\"P\n" +
	"\n" +
	"GateResult\x12\x12\n" +
	"\x04gate\x18\x01 \x01(\tR\x04gate\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\"\xa4\x01\n" +
	"\x0eVerifyResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x0e\n" +
	"\x02ok\x18\x04 \x01(\bR\x02ok\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12,\n" +
	"\x05gates\x18\x06 \x03(\v2\x16.rollops.v1.GateResultR\x05gates\"?\n" +
	"\rFreezeRequest\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"@\n" +
	"\x0eFreezeResponse\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2\x89\x05\n" +
	"\x0eRolloutService\x129\n" +
	"\x04Plan\x12\x17.rollops.v1.PlanRequest\x1a\x18.rollops.v1.PlanResponse\x12<\n" +
	"\x05Apply\x12\x18.rollops.v1.ApplyRequest\x1a\x19.rollops.v1.ApplyResponse\x12?\n" +
	"\x06Status\x12\x19.rollops.v1.StatusRequest\x1a\x1a.rollops.v1.StatusResponse\x12E\n" +
	"\bRollback\x12\x1b.rollops.v1.RollbackRequest\x1a\x1c.rollops.v1.RollbackResponse\x12N\n" +
	"\aApprove\x12 .rollops.v1.RolloutActionRequest\x1a!.rollops.v1.RolloutActionResponse\x12M\n" +
	"\x06Reject\x12 .rollops.v1.RolloutActionRequest\x1a!.rollops.v1.RolloutActionResponse\x12N\n" +
	"\aPromote\x12 .rollops.v1.RolloutActionRequest\x1a!.rollops.v1.RolloutActionResponse\x12F\n" +
	"\x06Verify\x12 .rollops.v1.RolloutActionRequest\x1a\x1a.rollops.v1.VerifyResponse\x12?\n" +
	"\x06Freeze\x12\x19.rollops.v1.FreezeRequest\x1a\x1a.rollops.v1.FreezeResponseB=Z;go.klarlabs.de/rollops/internal/grpcapi/rollopsv1;rollopsv1b\x06proto3"

var (
	file_rollops_v1_rollops_proto_rawDescOnce sync.Once
	file_rollops_v1_rollops_proto_rawDescData []byte
)

func file_rollops_v1_rollops_proto_rawDescGZIP() []byte {
	file_rollops_v1_rollops_proto_rawDescOnce.Do(func() {
		file_rollops_v1_rollops_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rollops_v1_rollops_proto_rawDesc), len(file_rollops_v1_rollops_proto_rawDesc)))
	})
	return file_rollops_v1_rollops_proto_rawDescData
}

var file_rollops_v1_rollops_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_rollops_v1_rollops_proto_goTypes = []any{
	(*PlanRequest)(nil),           // 0: rollops.v1.PlanRequest
	(*PlanResponse)(nil),          // 1: rollops.v1.PlanResponse
	(*ApplyRequest)(nil),          // 2: rollops.v1.ApplyRequest
	(*ApplyResponse)(nil),         // 3: rollops.v1.ApplyResponse
	(*StatusRequest)(nil),         // 4: rollops.v1.StatusRequest
	(*StatusResponse)(nil),        // 5: rollops.v1.StatusResponse
	(*RollbackRequest)(nil),       // 6: rollops.v1.RollbackRequest
	(*RollbackResponse)(nil),      // 7: rollops.v1.RollbackResponse
	(*RolloutActionRequest)(nil),  // 8: rollops.v1.RolloutActionRequest
	(*RolloutActionResponse)(nil), // 9: rollops.v1.RolloutActionResponse
	(*GateResult)(nil),            // 10: rollops.v1.GateResult
	(*VerifyResponse)(nil),        // 11: rollops.v1.VerifyResponse
	(*FreezeRequest)(nil),         // 12: rollops.v1.FreezeRequest
	(*FreezeResponse)(nil),        // 13: rollops.v1.FreezeResponse
}
var file_rollops_v1_rollops_proto_depIdxs = []int32{
	10, // 0: rollops.v1.VerifyResponse.gates:type_name -> rollops.v1.GateResult
	0,  // 1: rollops.v1.RolloutService.Plan:input_type -> rollops.v1.PlanRequest
	2,  // 2: rollops.v1.RolloutService.Apply:input_type -> rollops.v1.ApplyRequest
	4,  // 3: rollops.v1.RolloutService.Status:input_type -> rollops.v1.StatusRequest
	6,  // 4: rollops.v1.RolloutService.Rollback:input_type -> rollops.v1.RollbackRequest
	8,  // 5: rollops.v1.RolloutService.Approve:input_type -> rollops.v1.RolloutActionRequest
	8,  // 6: rollops.v1.RolloutService.Reject:input_type -> rollops.v1.RolloutActionRequest
	8,  // 7: rollops.v1.RolloutService.Promote:input_type -> rollops.v1.RolloutActionRequest
	8,  // 8: rollops.v1.RolloutService.Verify:input_type -> rollops.v1.RolloutActionRequest
	12, // 9: rollops.v1.RolloutService.Freeze:input_type -> rollops.v1.FreezeRequest
	1,  // 10: rollops.v1.RolloutService.Plan:output_type -> rollops.v1.PlanResponse
	3,  // 11: rollops.v1.RolloutService.Apply:output_type -> rollops.v1.ApplyResponse
	5,  // 12: rollops.v1.RolloutService.Status:output_type -> rollops.v1.StatusResponse
	7,  // 13: rollops.v1.RolloutService.Rollback:output_type -> rollops.v1.RollbackResponse
	9,  // 14: rollops.v1.RolloutService.Approve:output_type -> rollops.v1.RolloutActionResponse
	9,  // 15: rollops.v1.RolloutService.Reject:output_type -> rollops.v1.RolloutActionResponse
	9,  // 16: rollops.v1.RolloutService.Promote:output_type -> rollops.v1.RolloutActionResponse
	11, // 17: rollops.v1.RolloutService.Verify:output_type -> rollops.v1.VerifyResponse
	13, // 18: rollops.v1.RolloutService.Freeze:output_type -> rollops.v1.FreezeResponse
	10, // [10:19] is the sub-list for method output_type
	1,  // [1:10] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_rollops_v1_rollops_proto_init() }
func file_rollops_v1_rollops_proto_init() {
	if File_rollops_v1_rollops_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rollops_v1_rollops_proto_rawDesc), len(file_rollops_v1_rollops_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rollops_v1_rollops_proto_goTypes,
		DependencyIndexes: file_rollops_v1_rollops_proto_depIdxs,
		MessageInfos:      file_rollops_v1_rollops_proto_msgTypes,
	}.Build()
	File_rollops_v1_rollops_proto = out.File
	file_rollops_v1_rollops_proto_goTypes = nil
	file_rollops_v1_rollops_proto_depIdxs = nil
}
