// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: rollops/v2/rollops.proto

// The v2 API as gRPC sees it.
//
// This is a projection of internal/api/v2, not a second definition of it. The
// semantics — what a plan is, when a retry replays, what a missing project
// means — are settled in that package and every transport carries the same
// answers (§23.1). What is decided here is only how they are spelled on a wire.
//
// Three rules from §24 shape most of what follows. Closed sets are enums, not
// strings: an enum is checkable by a generated client, where a string is a
// value somebody has to look up. Open sets stay strings, because an enum whose
// members a plugin supplies would make every new verifier a breaking change to
// this file. And nothing here is a domain aggregate — these messages mirror the
// API's views, so renaming a field inside the domain is not an API change, and
// a configuration key can be named without its value being on the wire
// (INV-012).
//
// The enums are held to the domain by a test over the vocabularies the domain
// publishes — deployment.Statuses(), environment.Kinds() and the rest — so a
// value added there and forgotten here is a build failure rather than a caller
// being told the status does not exist.

package rollopsv2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RollOps_CreateProject_FullMethodName        = "/rollops.v2.RollOps/CreateProject"
	RollOps_GetProject_FullMethodName           = "/rollops.v2.RollOps/GetProject"
	RollOps_ListProjects_FullMethodName         = "/rollops.v2.RollOps/ListProjects"
	RollOps_CreateEnvironment_FullMethodName    = "/rollops.v2.RollOps/CreateEnvironment"
	RollOps_GetEnvironment_FullMethodName       = "/rollops.v2.RollOps/GetEnvironment"
	RollOps_ListEnvironments_FullMethodName     = "/rollops.v2.RollOps/ListEnvironments"
	RollOps_RegisterArtifact_FullMethodName     = "/rollops.v2.RollOps/RegisterArtifact"
	RollOps_GetArtifact_FullMethodName          = "/rollops.v2.RollOps/GetArtifact"
	RollOps_ListArtifacts_FullMethodName        = "/rollops.v2.RollOps/ListArtifacts"
	RollOps_CreateRelease_FullMethodName        = "/rollops.v2.RollOps/CreateRelease"
	RollOps_GetRelease_FullMethodName           = "/rollops.v2.RollOps/GetRelease"
	RollOps_ListReleases_FullMethodName         = "/rollops.v2.RollOps/ListReleases"
	RollOps_CreatePlan_FullMethodName           = "/rollops.v2.RollOps/CreatePlan"
	RollOps_GetPlan_FullMethodName              = "/rollops.v2.RollOps/GetPlan"
	RollOps_ApplyPlan_FullMethodName            = "/rollops.v2.RollOps/ApplyPlan"
	RollOps_GetDeployment_FullMethodName        = "/rollops.v2.RollOps/GetDeployment"
	RollOps_ListDeployments_FullMethodName      = "/rollops.v2.RollOps/ListDeployments"
	RollOps_ApproveDeployment_FullMethodName    = "/rollops.v2.RollOps/ApproveDeployment"
	RollOps_CancelDeployment_FullMethodName     = "/rollops.v2.RollOps/CancelDeployment"
	RollOps_PromoteDeployment_FullMethodName    = "/rollops.v2.RollOps/PromoteDeployment"
	RollOps_RollbackDeployment_FullMethodName   = "/rollops.v2.RollOps/RollbackDeployment"
	RollOps_VerifyDeployment_FullMethodName     = "/rollops.v2.RollOps/VerifyDeployment"
	RollOps_GetVerificationRun_FullMethodName   = "/rollops.v2.RollOps/GetVerificationRun"
	RollOps_ListDeploymentEvents_FullMethodName = "/rollops.v2.RollOps/ListDeploymentEvents"
)

// RollOpsClient is the client API for RollOps service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RollOps is the v2 surface: projects and the environments they deploy to,
// artifacts and the releases that fix them, the plans that say what a
// deployment would change, and the timeline of what happened.
//
// No request carries an actor. Who is calling is established by the transport's
// authentication and injected server-side, exactly as the HTTP surface does —
// a field for it would be a field a caller could fill in with somebody else's
// name.
type RollOpsClient interface {
	// CreateProject opens a namespace.
	CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*Project, error)
	// GetProject returns one project.
	GetProject(ctx context.Context, in *GetProjectRequest, opts ...grpc.CallOption) (*Project, error)
	// ListProjects returns a page of projects.
	ListProjects(ctx context.Context, in *ListProjectsRequest, opts ...grpc.CallOption) (*ListProjectsResponse, error)
	// CreateEnvironment declares a place to deploy to.
	CreateEnvironment(ctx context.Context, in *CreateEnvironmentRequest, opts ...grpc.CallOption) (*Environment, error)
	// GetEnvironment returns one environment.
	GetEnvironment(ctx context.Context, in *GetEnvironmentRequest, opts ...grpc.CallOption) (*Environment, error)
	// ListEnvironments returns a page of one project's environments.
	ListEnvironments(ctx context.Context, in *ListEnvironmentsRequest, opts ...grpc.CallOption) (*ListEnvironmentsResponse, error)
	// RegisterArtifact records where a built thing is and what it must hash to.
	RegisterArtifact(ctx context.Context, in *RegisterArtifactRequest, opts ...grpc.CallOption) (*Artifact, error)
	// GetArtifact returns one artifact.
	GetArtifact(ctx context.Context, in *GetArtifactRequest, opts ...grpc.CallOption) (*Artifact, error)
	// ListArtifacts returns a page of one project's artifacts.
	ListArtifacts(ctx context.Context, in *ListArtifactsRequest, opts ...grpc.CallOption) (*ListArtifactsResponse, error)
	// CreateRelease fixes the set of artifacts a release will deploy.
	CreateRelease(ctx context.Context, in *CreateReleaseRequest, opts ...grpc.CallOption) (*Release, error)
	// GetRelease returns one release.
	GetRelease(ctx context.Context, in *GetReleaseRequest, opts ...grpc.CallOption) (*Release, error)
	// ListReleases returns a page of one project's releases.
	ListReleases(ctx context.Context, in *ListReleasesRequest, opts ...grpc.CallOption) (*ListReleasesResponse, error)
	// CreatePlan works out what deploying a release would change and has policy
	// rule on it. It touches no substrate (§8.2).
	CreatePlan(ctx context.Context, in *CreatePlanRequest, opts ...grpc.CallOption) (*Plan, error)
	// GetPlan returns one plan.
	GetPlan(ctx context.Context, in *GetPlanRequest, opts ...grpc.CallOption) (*Plan, error)
	// ApplyPlan admits a deployment for a stored plan and returns as soon as the
	// deployment is recorded (§23.3). A plan with unmet requirements comes back
	// awaiting approval rather than as an error.
	ApplyPlan(ctx context.Context, in *ApplyPlanRequest, opts ...grpc.CallOption) (*Deployment, error)
	// GetDeployment returns one deployment.
	GetDeployment(ctx context.Context, in *GetDeploymentRequest, opts ...grpc.CallOption) (*Deployment, error)
	// ListDeployments returns a page of one environment's deployments.
	ListDeployments(ctx context.Context, in *ListDeploymentsRequest, opts ...grpc.CallOption) (*ListDeploymentsResponse, error)
	// ApproveDeployment records one principal's answer about a gated deployment.
	ApproveDeployment(ctx context.Context, in *ApproveDeploymentRequest, opts ...grpc.CallOption) (*Deployment, error)
	// CancelDeployment stops a deployment. Nothing already applied is undone.
	CancelDeployment(ctx context.Context, in *CancelDeploymentRequest, opts ...grpc.CallOption) (*Deployment, error)
	// PromoteDeployment widens a deployment that is serving.
	PromoteDeployment(ctx context.Context, in *PromoteDeploymentRequest, opts ...grpc.CallOption) (*Deployment, error)
	// RollbackDeployment returns a deployment to the release it replaced.
	RollbackDeployment(ctx context.Context, in *RollbackDeploymentRequest, opts ...grpc.CallOption) (*Deployment, error)
	// VerifyDeployment runs the environment's checks and returns what they found.
	// A failing verdict is a successful call: the question was answered.
	VerifyDeployment(ctx context.Context, in *VerifyDeploymentRequest, opts ...grpc.CallOption) (*VerifyDeploymentResponse, error)
	// GetVerificationRun returns what one verification concluded. This is where a
	// timeline entry leads — the completion event carries the run id.
	GetVerificationRun(ctx context.Context, in *GetVerificationRunRequest, opts ...grpc.CallOption) (*VerificationRun, error)
	// ListDeploymentEvents returns a page of one deployment's events, oldest
	// first.
	ListDeploymentEvents(ctx context.Context, in *ListDeploymentEventsRequest, opts ...grpc.CallOption) (*ListDeploymentEventsResponse, error)
}

type rollOpsClient struct {
	cc grpc.ClientConnInterface
}

func NewRollOpsClient(cc grpc.ClientConnInterface) RollOpsClient {
	return &rollOpsClient{cc}
}

func (c *rollOpsClient) CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*Project, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Project)
	err := c.cc.Invoke(ctx, RollOps_CreateProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rollOpsClient) GetProject(ctx context.Context, in *GetProjectRequest, opts ...grpc.CallOption) (*Project, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Project)
	err := c.cc.Invoke(ctx, RollOps_GetProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rollOpsClient) ListProjects(ctx context.Context, in *ListProjectsRequest, opts ...grpc.CallOption) (*ListProjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProjectsResponse)
	err := c.cc.Invoke(ctx, RollOps_ListProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rollOpsClient) CreateEnvironment(ctx context.Context, in *CreateEnvironmentRequest, opts ...grpc.CallOption) (*Environment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Environment)
	err := c.cc.Invoke(ctx, RollOps_CreateEnvironment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rollOpsClient) GetEnvironment(ctx context.Context, in *GetEnvironmentRequest, opts ...grpc.CallOption) (*Environment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Environment)
	err := c.cc.Invoke(ctx, RollOps_GetEnvironment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rollOpsClient) ListEnvironments(ctx context.Context, in *ListEnvironmentsRequest, opts ...grpc.CallOption) (*ListEnvironmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEnvironmentsResponse)
	err := c.cc.Invoke(ctx, RollOps_ListEnvironments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rollOpsClient) RegisterArtifact(ctx context.Context, in *RegisterArtifactRequest, opts ...grpc.CallOption) (*Artifact, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Artifact)
	err := c.cc.Invoke(ctx, RollOps_RegisterArtifact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rollOpsClient) GetArtifact(ctx context.Context, in *GetArtifactRequest, opts ...grpc.CallOption) (*Artifact, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Artifact)
	err := c.cc.Invoke(ctx, RollOps_GetArtifact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rollOpsClient) ListArtifacts(ctx context.Context, in *ListArtifactsRequest, opts ...grpc.CallOption) (*ListArtifactsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListArtifactsResponse)
	err := c.cc.Invoke(ctx, RollOps_ListArtifacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rollOpsClient) CreateRelease(ctx context.Context, in *CreateReleaseRequest, opts ...grpc.CallOption) (*Release, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Release)
	err := c.cc.Invoke(ctx, RollOps_CreateRelease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rollOpsClient) GetRelease(ctx context.Context, in *GetReleaseRequest, opts ...grpc.CallOption) (*Release, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Release)
	err := c.cc.Invoke(ctx, RollOps_GetRelease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rollOpsClient) ListReleases(ctx context.Context, in *ListReleasesRequest, opts ...grpc.CallOption) (*ListReleasesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReleasesResponse)
	err := c.cc.Invoke(ctx, RollOps_ListReleases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rollOpsClient) CreatePlan(ctx context.Context, in *CreatePlanRequest, opts ...grpc.CallOption) (*Plan, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Plan)
	err := c.cc.Invoke(ctx, RollOps_CreatePlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rollOpsClient) GetPlan(ctx context.Context, in *GetPlanRequest, opts ...grpc.CallOption) (*Plan, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Plan)
	err := c.cc.Invoke(ctx, RollOps_GetPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rollOpsClient) ApplyPlan(ctx context.Context, in *ApplyPlanRequest, opts ...grpc.CallOption) (*Deployment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Deployment)
	err := c.cc.Invoke(ctx, RollOps_ApplyPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rollOpsClient) GetDeployment(ctx context.Context, in *GetDeploymentRequest, opts ...grpc.CallOption) (*Deployment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Deployment)
	err := c.cc.Invoke(ctx, RollOps_GetDeployment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rollOpsClient) ListDeployments(ctx context.Context, in *ListDeploymentsRequest, opts ...grpc.CallOption) (*ListDeploymentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDeploymentsResponse)
	err := c.cc.Invoke(ctx, RollOps_ListDeployments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rollOpsClient) ApproveDeployment(ctx context.Context, in *ApproveDeploymentRequest, opts ...grpc.CallOption) (*Deployment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Deployment)
	err := c.cc.Invoke(ctx, RollOps_ApproveDeployment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rollOpsClient) CancelDeployment(ctx context.Context, in *CancelDeploymentRequest, opts ...grpc.CallOption) (*Deployment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Deployment)
	err := c.cc.Invoke(ctx, RollOps_CancelDeployment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rollOpsClient) PromoteDeployment(ctx context.Context, in *PromoteDeploymentRequest, opts ...grpc.CallOption) (*Deployment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Deployment)
	err := c.cc.Invoke(ctx, RollOps_PromoteDeployment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rollOpsClient) RollbackDeployment(ctx context.Context, in *RollbackDeploymentRequest, opts ...grpc.CallOption) (*Deployment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Deployment)
	err := c.cc.Invoke(ctx, RollOps_RollbackDeployment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rollOpsClient) VerifyDeployment(ctx context.Context, in *VerifyDeploymentRequest, opts ...grpc.CallOption) (*VerifyDeploymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyDeploymentResponse)
	err := c.cc.Invoke(ctx, RollOps_VerifyDeployment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rollOpsClient) GetVerificationRun(ctx context.Context, in *GetVerificationRunRequest, opts ...grpc.CallOption) (*VerificationRun, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerificationRun)
	err := c.cc.Invoke(ctx, RollOps_GetVerificationRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rollOpsClient) ListDeploymentEvents(ctx context.Context, in *ListDeploymentEventsRequest, opts ...grpc.CallOption) (*ListDeploymentEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDeploymentEventsResponse)
	err := c.cc.Invoke(ctx, RollOps_ListDeploymentEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RollOpsServer is the server API for RollOps service.
// All implementations must embed UnimplementedRollOpsServer
// for forward compatibility.
//
// RollOps is the v2 surface: projects and the environments they deploy to,
// artifacts and the releases that fix them, the plans that say what a
// deployment would change, and the timeline of what happened.
//
// No request carries an actor. Who is calling is established by the transport's
// authentication and injected server-side, exactly as the HTTP surface does —
// a field for it would be a field a caller could fill in with somebody else's
// name.
type RollOpsServer interface {
	// CreateProject opens a namespace.
	CreateProject(context.Context, *CreateProjectRequest) (*Project, error)
	// GetProject returns one project.
	GetProject(context.Context, *GetProjectRequest) (*Project, error)
	// ListProjects returns a page of projects.
	ListProjects(context.Context, *ListProjectsRequest) (*ListProjectsResponse, error)
	// CreateEnvironment declares a place to deploy to.
	CreateEnvironment(context.Context, *CreateEnvironmentRequest) (*Environment, error)
	// GetEnvironment returns one environment.
	GetEnvironment(context.Context, *GetEnvironmentRequest) (*Environment, error)
	// ListEnvironments returns a page of one project's environments.
	ListEnvironments(context.Context, *ListEnvironmentsRequest) (*ListEnvironmentsResponse, error)
	// RegisterArtifact records where a built thing is and what it must hash to.
	RegisterArtifact(context.Context, *RegisterArtifactRequest) (*Artifact, error)
	// GetArtifact returns one artifact.
	GetArtifact(context.Context, *GetArtifactRequest) (*Artifact, error)
	// ListArtifacts returns a page of one project's artifacts.
	ListArtifacts(context.Context, *ListArtifactsRequest) (*ListArtifactsResponse, error)
	// CreateRelease fixes the set of artifacts a release will deploy.
	CreateRelease(context.Context, *CreateReleaseRequest) (*Release, error)
	// GetRelease returns one release.
	GetRelease(context.Context, *GetReleaseRequest) (*Release, error)
	// ListReleases returns a page of one project's releases.
	ListReleases(context.Context, *ListReleasesRequest) (*ListReleasesResponse, error)
	// CreatePlan works out what deploying a release would change and has policy
	// rule on it. It touches no substrate (§8.2).
	CreatePlan(context.Context, *CreatePlanRequest) (*Plan, error)
	// GetPlan returns one plan.
	GetPlan(context.Context, *GetPlanRequest) (*Plan, error)
	// ApplyPlan admits a deployment for a stored plan and returns as soon as the
	// deployment is recorded (§23.3). A plan with unmet requirements comes back
	// awaiting approval rather than as an error.
	ApplyPlan(context.Context, *ApplyPlanRequest) (*Deployment, error)
	// GetDeployment returns one deployment.
	GetDeployment(context.Context, *GetDeploymentRequest) (*Deployment, error)
	// ListDeployments returns a page of one environment's deployments.
	ListDeployments(context.Context, *ListDeploymentsRequest) (*ListDeploymentsResponse, error)
	// ApproveDeployment records one principal's answer about a gated deployment.
	ApproveDeployment(context.Context, *ApproveDeploymentRequest) (*Deployment, error)
	// CancelDeployment stops a deployment. Nothing already applied is undone.
	CancelDeployment(context.Context, *CancelDeploymentRequest) (*Deployment, error)
	// PromoteDeployment widens a deployment that is serving.
	PromoteDeployment(context.Context, *PromoteDeploymentRequest) (*Deployment, error)
	// RollbackDeployment returns a deployment to the release it replaced.
	RollbackDeployment(context.Context, *RollbackDeploymentRequest) (*Deployment, error)
	// VerifyDeployment runs the environment's checks and returns what they found.
	// A failing verdict is a successful call: the question was answered.
	VerifyDeployment(context.Context, *VerifyDeploymentRequest) (*VerifyDeploymentResponse, error)
	// GetVerificationRun returns what one verification concluded. This is where a
	// timeline entry leads — the completion event carries the run id.
	GetVerificationRun(context.Context, *GetVerificationRunRequest) (*VerificationRun, error)
	// ListDeploymentEvents returns a page of one deployment's events, oldest
	// first.
	ListDeploymentEvents(context.Context, *ListDeploymentEventsRequest) (*ListDeploymentEventsResponse, error)
	mustEmbedUnimplementedRollOpsServer()
}

// UnimplementedRollOpsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRollOpsServer struct{}

func (UnimplementedRollOpsServer) CreateProject(context.Context, *CreateProjectRequest) (*Project, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProject not implemented")
}
func (UnimplementedRollOpsServer) GetProject(context.Context, *GetProjectRequest) (*Project, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProject not implemented")
}
func (UnimplementedRollOpsServer) ListProjects(context.Context, *ListProjectsRequest) (*ListProjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProjects not implemented")
}
func (UnimplementedRollOpsServer) CreateEnvironment(context.Context, *CreateEnvironmentRequest) (*Environment, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEnvironment not implemented")
}
func (UnimplementedRollOpsServer) GetEnvironment(context.Context, *GetEnvironmentRequest) (*Environment, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEnvironment not implemented")
}
func (UnimplementedRollOpsServer) ListEnvironments(context.Context, *ListEnvironmentsRequest) (*ListEnvironmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEnvironments not implemented")
}
func (UnimplementedRollOpsServer) RegisterArtifact(context.Context, *RegisterArtifactRequest) (*Artifact, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterArtifact not implemented")
}
func (UnimplementedRollOpsServer) GetArtifact(context.Context, *GetArtifactRequest) (*Artifact, error) {
	return nil, status.Error(codes.Unimplemented, "method GetArtifact not implemented")
}
func (UnimplementedRollOpsServer) ListArtifacts(context.Context, *ListArtifactsRequest) (*ListArtifactsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListArtifacts not implemented")
}
func (UnimplementedRollOpsServer) CreateRelease(context.Context, *CreateReleaseRequest) (*Release, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRelease not implemented")
}
func (UnimplementedRollOpsServer) GetRelease(context.Context, *GetReleaseRequest) (*Release, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRelease not implemented")
}
func (UnimplementedRollOpsServer) ListReleases(context.Context, *ListReleasesRequest) (*ListReleasesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListReleases not implemented")
}
func (UnimplementedRollOpsServer) CreatePlan(context.Context, *CreatePlanRequest) (*Plan, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePlan not implemented")
}
func (UnimplementedRollOpsServer) GetPlan(context.Context, *GetPlanRequest) (*Plan, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlan not implemented")
}
func (UnimplementedRollOpsServer) ApplyPlan(context.Context, *ApplyPlanRequest) (*Deployment, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyPlan not implemented")
}
func (UnimplementedRollOpsServer) GetDeployment(context.Context, *GetDeploymentRequest) (*Deployment, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeployment not implemented")
}
func (UnimplementedRollOpsServer) ListDeployments(context.Context, *ListDeploymentsRequest) (*ListDeploymentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDeployments not implemented")
}
func (UnimplementedRollOpsServer) ApproveDeployment(context.Context, *ApproveDeploymentRequest) (*Deployment, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveDeployment not implemented")
}
func (UnimplementedRollOpsServer) CancelDeployment(context.Context, *CancelDeploymentRequest) (*Deployment, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelDeployment not implemented")
}
func (UnimplementedRollOpsServer) PromoteDeployment(context.Context, *PromoteDeploymentRequest) (*Deployment, error) {
	return nil, status.Error(codes.Unimplemented, "method PromoteDeployment not implemented")
}
func (UnimplementedRollOpsServer) RollbackDeployment(context.Context, *RollbackDeploymentRequest) (*Deployment, error) {
	return nil, status.Error(codes.Unimplemented, "method RollbackDeployment not implemented")
}
func (UnimplementedRollOpsServer) VerifyDeployment(context.Context, *VerifyDeploymentRequest) (*VerifyDeploymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyDeployment not implemented")
}
func (UnimplementedRollOpsServer) GetVerificationRun(context.Context, *GetVerificationRunRequest) (*VerificationRun, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVerificationRun not implemented")
}
func (UnimplementedRollOpsServer) ListDeploymentEvents(context.Context, *ListDeploymentEventsRequest) (*ListDeploymentEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDeploymentEvents not implemented")
}
func (UnimplementedRollOpsServer) mustEmbedUnimplementedRollOpsServer() {}
func (UnimplementedRollOpsServer) testEmbeddedByValue()                 {}

// UnsafeRollOpsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RollOpsServer will
// result in compilation errors.
type UnsafeRollOpsServer interface {
	mustEmbedUnimplementedRollOpsServer()
}

func RegisterRollOpsServer(s grpc.ServiceRegistrar, srv RollOpsServer) {
	// If the following call panics, it indicates UnimplementedRollOpsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RollOps_ServiceDesc, srv)
}

func _RollOps_CreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RollOpsServer).CreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RollOps_CreateProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RollOpsServer).CreateProject(ctx, req.(*CreateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RollOps_GetProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RollOpsServer).GetProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RollOps_GetProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RollOpsServer).GetProject(ctx, req.(*GetProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RollOps_ListProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RollOpsServer).ListProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RollOps_ListProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RollOpsServer).ListProjects(ctx, req.(*ListProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RollOps_CreateEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RollOpsServer).CreateEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RollOps_CreateEnvironment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RollOpsServer).CreateEnvironment(ctx, req.(*CreateEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RollOps_GetEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RollOpsServer).GetEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RollOps_GetEnvironment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RollOpsServer).GetEnvironment(ctx, req.(*GetEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RollOps_ListEnvironments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEnvironmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RollOpsServer).ListEnvironments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RollOps_ListEnvironments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RollOpsServer).ListEnvironments(ctx, req.(*ListEnvironmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RollOps_RegisterArtifact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterArtifactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RollOpsServer).RegisterArtifact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RollOps_RegisterArtifact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RollOpsServer).RegisterArtifact(ctx, req.(*RegisterArtifactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RollOps_GetArtifact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArtifactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RollOpsServer).GetArtifact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RollOps_GetArtifact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RollOpsServer).GetArtifact(ctx, req.(*GetArtifactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RollOps_ListArtifacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListArtifactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RollOpsServer).ListArtifacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RollOps_ListArtifacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RollOpsServer).ListArtifacts(ctx, req.(*ListArtifactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RollOps_CreateRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RollOpsServer).CreateRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RollOps_CreateRelease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RollOpsServer).CreateRelease(ctx, req.(*CreateReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RollOps_GetRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RollOpsServer).GetRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RollOps_GetRelease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RollOpsServer).GetRelease(ctx, req.(*GetReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RollOps_ListReleases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReleasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RollOpsServer).ListReleases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RollOps_ListReleases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RollOpsServer).ListReleases(ctx, req.(*ListReleasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RollOps_CreatePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RollOpsServer).CreatePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RollOps_CreatePlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RollOpsServer).CreatePlan(ctx, req.(*CreatePlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RollOps_GetPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RollOpsServer).GetPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RollOps_GetPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RollOpsServer).GetPlan(ctx, req.(*GetPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RollOps_ApplyPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RollOpsServer).ApplyPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RollOps_ApplyPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RollOpsServer).ApplyPlan(ctx, req.(*ApplyPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RollOps_GetDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RollOpsServer).GetDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RollOps_GetDeployment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RollOpsServer).GetDeployment(ctx, req.(*GetDeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RollOps_ListDeployments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDeploymentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RollOpsServer).ListDeployments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RollOps_ListDeployments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RollOpsServer).ListDeployments(ctx, req.(*ListDeploymentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RollOps_ApproveDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveDeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RollOpsServer).ApproveDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RollOps_ApproveDeployment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RollOpsServer).ApproveDeployment(ctx, req.(*ApproveDeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RollOps_CancelDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelDeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RollOpsServer).CancelDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RollOps_CancelDeployment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RollOpsServer).CancelDeployment(ctx, req.(*CancelDeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RollOps_PromoteDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromoteDeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RollOpsServer).PromoteDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RollOps_PromoteDeployment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RollOpsServer).PromoteDeployment(ctx, req.(*PromoteDeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RollOps_RollbackDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackDeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RollOpsServer).RollbackDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RollOps_RollbackDeployment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RollOpsServer).RollbackDeployment(ctx, req.(*RollbackDeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RollOps_VerifyDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyDeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RollOpsServer).VerifyDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RollOps_VerifyDeployment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RollOpsServer).VerifyDeployment(ctx, req.(*VerifyDeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RollOps_GetVerificationRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVerificationRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RollOpsServer).GetVerificationRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RollOps_GetVerificationRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RollOpsServer).GetVerificationRun(ctx, req.(*GetVerificationRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RollOps_ListDeploymentEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDeploymentEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RollOpsServer).ListDeploymentEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RollOps_ListDeploymentEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RollOpsServer).ListDeploymentEvents(ctx, req.(*ListDeploymentEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RollOps_ServiceDesc is the grpc.ServiceDesc for RollOps service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RollOps_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rollops.v2.RollOps",
	HandlerType: (*RollOpsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProject",
			Handler:    _RollOps_CreateProject_Handler,
		},
		{
			MethodName: "GetProject",
			Handler:    _RollOps_GetProject_Handler,
		},
		{
			MethodName: "ListProjects",
			Handler:    _RollOps_ListProjects_Handler,
		},
		{
			MethodName: "CreateEnvironment",
			Handler:    _RollOps_CreateEnvironment_Handler,
		},
		{
			MethodName: "GetEnvironment",
			Handler:    _RollOps_GetEnvironment_Handler,
		},
		{
			MethodName: "ListEnvironments",
			Handler:    _RollOps_ListEnvironments_Handler,
		},
		{
			MethodName: "RegisterArtifact",
			Handler:    _RollOps_RegisterArtifact_Handler,
		},
		{
			MethodName: "GetArtifact",
			Handler:    _RollOps_GetArtifact_Handler,
		},
		{
			MethodName: "ListArtifacts",
			Handler:    _RollOps_ListArtifacts_Handler,
		},
		{
			MethodName: "CreateRelease",
			Handler:    _RollOps_CreateRelease_Handler,
		},
		{
			MethodName: "GetRelease",
			Handler:    _RollOps_GetRelease_Handler,
		},
		{
			MethodName: "ListReleases",
			Handler:    _RollOps_ListReleases_Handler,
		},
		{
			MethodName: "CreatePlan",
			Handler:    _RollOps_CreatePlan_Handler,
		},
		{
			MethodName: "GetPlan",
			Handler:    _RollOps_GetPlan_Handler,
		},
		{
			MethodName: "ApplyPlan",
			Handler:    _RollOps_ApplyPlan_Handler,
		},
		{
			MethodName: "GetDeployment",
			Handler:    _RollOps_GetDeployment_Handler,
		},
		{
			MethodName: "ListDeployments",
			Handler:    _RollOps_ListDeployments_Handler,
		},
		{
			MethodName: "ApproveDeployment",
			Handler:    _RollOps_ApproveDeployment_Handler,
		},
		{
			MethodName: "CancelDeployment",
			Handler:    _RollOps_CancelDeployment_Handler,
		},
		{
			MethodName: "PromoteDeployment",
			Handler:    _RollOps_PromoteDeployment_Handler,
		},
		{
			MethodName: "RollbackDeployment",
			Handler:    _RollOps_RollbackDeployment_Handler,
		},
		{
			MethodName: "VerifyDeployment",
			Handler:    _RollOps_VerifyDeployment_Handler,
		},
		{
			MethodName: "GetVerificationRun",
			Handler:    _RollOps_GetVerificationRun_Handler,
		},
		{
			MethodName: "ListDeploymentEvents",
			Handler:    _RollOps_ListDeploymentEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rollops/v2/rollops.proto",
}
